// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_token.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_token (user_id, token_hash)
VALUES ($1, $2)
RETURNING id, user_id, created_at
`

type CreateAuthTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
}

type CreateAuthTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

// Bearer トークンの hash を保存する（平文は保存しない）。
func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (CreateAuthTokenRow, error) {
	row := q.db.QueryRow(ctx, createAuthToken, arg.UserID, arg.TokenHash)
	var i CreateAuthTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getActiveUserByTokenHash = `-- name: GetActiveUserByTokenHash :one
SELECT u.id, u.role, u.suspended_at
FROM auth_token t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.revoked_at IS NULL
`

type GetActiveUserByTokenHashRow struct {
	ID          uuid.UUID
	Role        string
	SuspendedAt pgtype.Timestamptz
}

// 失効していないトークン hash から所有ユーザーを引く（認証 middleware が使う）。
func (q *Queries) GetActiveUserByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserByTokenHash, tokenHash)
	var i GetActiveUserByTokenHashRow
	err := row.Scan(&i.ID, &i.Role, &i.SuspendedAt)
	return i, err
}

const revokeAuthToken = `-- name: RevokeAuthToken :exec
UPDATE auth_token
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeAuthToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeAuthToken, tokenHash)
	return err
}

const touchAuthToken = `-- name: TouchAuthToken :exec
UPDATE auth_token
SET last_used_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchAuthToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchAuthToken, tokenHash)
	return err
}
