// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: child_safety_alert.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChildSafetyAlert = `-- name: CreateChildSafetyAlert :exec
INSERT INTO child_safety_alert (tanzaku_id, author_id, body_snapshot, source_report_id)
VALUES ($1, $2, $3, $4)
`

type CreateChildSafetyAlertParams struct {
	TanzakuID      pgtype.UUID
	AuthorID       uuid.UUID
	BodySnapshot   string
	SourceReportID pgtype.UUID
}

// 児童保全のホールドを作る（匿名化後も判断材料を失わないよう本文をスナップショット）。
func (q *Queries) CreateChildSafetyAlert(ctx context.Context, arg CreateChildSafetyAlertParams) error {
	_, err := q.db.Exec(ctx, createChildSafetyAlert,
		arg.TanzakuID,
		arg.AuthorID,
		arg.BodySnapshot,
		arg.SourceReportID,
	)
	return err
}
