// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :exec
INSERT INTO delivery (tanzaku_id, recipient_id, delivered_on)
VALUES ($1, $2, $3)
`

type CreateDeliveryParams struct {
	TanzakuID   uuid.UUID
	RecipientID uuid.UUID
	DeliveredOn pgtype.Date
}

// 配信を記録する。tanzaku_id UNIQUE がユニキャストを、(recipient_id,delivered_on) UNIQUE が1日1回を守る。
func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.Exec(ctx, createDelivery, arg.TanzakuID, arg.RecipientID, arg.DeliveredOn)
	return err
}
