// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_ledger.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decrementCredit = `-- name: DecrementCredit :exec
UPDATE exchange_ledger
SET receive_credits = receive_credits - 1
WHERE user_id = $1
`

// 受信でクレジットを −1（非負は CHECK が守る）。
func (q *Queries) DecrementCredit(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementCredit, userID)
	return err
}

const getCredits = `-- name: GetCredits :one
SELECT receive_credits FROM exchange_ledger WHERE user_id = $1
`

func (q *Queries) GetCredits(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCredits, userID)
	var receive_credits int32
	err := row.Scan(&receive_credits)
	return receive_credits, err
}

const incrementCredit = `-- name: IncrementCredit :exec
INSERT INTO exchange_ledger (user_id, receive_credits)
VALUES ($1, 1)
ON CONFLICT (user_id) DO UPDATE SET receive_credits = exchange_ledger.receive_credits + 1
`

// 関門通過で互酬クレジットを +1（無ければ 1 で作る）。
func (q *Queries) IncrementCredit(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCredit, userID)
	return err
}

const listEligibleRecipients = `-- name: ListEligibleRecipients :many
SELECT el.user_id,
       (SELECT count(*) FROM tanzaku t
          WHERE t.status = 'pooled' AND t.author_id IS DISTINCT FROM el.user_id) AS assignable
FROM exchange_ledger el
JOIN users u ON u.id = el.user_id
WHERE el.receive_credits > 0
  AND u.suspended_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM delivery d
      WHERE d.recipient_id = el.user_id AND d.delivered_on = $1
  )
ORDER BY assignable ASC, el.user_id
`

type ListEligibleRecipientsRow struct {
	UserID     uuid.UUID
	Assignable int64
}

// 受信資格者（credits>0・当日未配信・未停止）を、割当可能枚数の少ない順に返す。
// 選択肢の少ない人を先に満たすことで、薄いプールでも公平に配る。
func (q *Queries) ListEligibleRecipients(ctx context.Context, deliveredOn pgtype.Date) ([]ListEligibleRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleRecipients, deliveredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleRecipientsRow
	for rows.Next() {
		var i ListEligibleRecipientsRow
		if err := rows.Scan(&i.UserID, &i.Assignable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
