// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gate_verdict.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const recordGateVerdict = `-- name: RecordGateVerdict :exec
INSERT INTO gate_verdict (subject_kind, subject_id, verdict, model, raw)
VALUES ($1, $2, $3, $4, $5)
`

type RecordGateVerdictParams struct {
	SubjectKind string
	SubjectID   uuid.UUID
	Verdict     string
	Model       *string
	Raw         []byte
}

// 判定を監査ログに残す（著者には露出しない）。
func (q *Queries) RecordGateVerdict(ctx context.Context, arg RecordGateVerdictParams) error {
	_, err := q.db.Exec(ctx, recordGateVerdict,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Verdict,
		arg.Model,
		arg.Raw,
	)
	return err
}
