// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ko_reference.sql

package sqlcdb

import (
	"context"
)

const getKoReference = `-- name: GetKoReference :one
SELECT ko, name, kana, meaning, sekki, season
FROM ko_reference
WHERE ko = $1
`

// 候番号からメタ（名称・読み・意味・節気・季節）を引く。
func (q *Queries) GetKoReference(ctx context.Context, ko int16) (KoReference, error) {
	row := q.db.QueryRow(ctx, getKoReference, ko)
	var i KoReference
	err := row.Scan(
		&i.Ko,
		&i.Name,
		&i.Kana,
		&i.Meaning,
		&i.Sekki,
		&i.Season,
	)
	return i, err
}

const listKoReference = `-- name: ListKoReference :many
SELECT ko, name, kana, meaning, sekki, season
FROM ko_reference
ORDER BY ko
`

// 全 72 候のメタを候番号順に返す（文箱の候別表示でメタを引くため）。
func (q *Queries) ListKoReference(ctx context.Context) ([]KoReference, error) {
	rows, err := q.db.Query(ctx, listKoReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KoReference
	for rows.Next() {
		var i KoReference
		if err := rows.Scan(
			&i.Ko,
			&i.Name,
			&i.Kana,
			&i.Meaning,
			&i.Sekki,
			&i.Season,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
