// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type KoReference struct {
	Ko      int16
	Name    string
	Kana    string
	Meaning string
	Sekki   int16
	Season  string
}

type Record struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Body      string
	KoWritten int16
	CreatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Role        string
	Reputation  int32
	SuspendedAt pgtype.Timestamptz
}
