// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_submission.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingSubmission = `-- name: CreatePendingSubmission :one
INSERT INTO pending_submission (author_id, source_record_id, body, ko_written, last_error)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreatePendingSubmissionParams struct {
	AuthorID       uuid.UUID
	SourceRecordID pgtype.UUID
	Body           string
	KoWritten      int16
	LastError      *string
}

// 判定が安全と確定しなかった投入を保留する（fail-closed）。body は投入時スナップショット。
func (q *Queries) CreatePendingSubmission(ctx context.Context, arg CreatePendingSubmissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPendingSubmission,
		arg.AuthorID,
		arg.SourceRecordID,
		arg.Body,
		arg.KoWritten,
		arg.LastError,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const incrementPendingAttempt = `-- name: IncrementPendingAttempt :exec
UPDATE pending_submission
SET attempts = attempts + 1, last_error = $2
WHERE id = $1
`

type IncrementPendingAttemptParams struct {
	ID        uuid.UUID
	LastError *string
}

// 判定が曖昧/エラーのまま据え置く（試行回数を進め、原因を残す）。
func (q *Queries) IncrementPendingAttempt(ctx context.Context, arg IncrementPendingAttemptParams) error {
	_, err := q.db.Exec(ctx, incrementPendingAttempt, arg.ID, arg.LastError)
	return err
}

const listAwaitingSubmissions = `-- name: ListAwaitingSubmissions :many
SELECT id, author_id, source_record_id, body, ko_written, attempts
FROM pending_submission
WHERE status = 'awaiting'
ORDER BY created_at ASC
LIMIT $1
`

type ListAwaitingSubmissionsRow struct {
	ID             uuid.UUID
	AuthorID       uuid.UUID
	SourceRecordID pgtype.UUID
	Body           string
	KoWritten      int16
	Attempts       int32
}

// 復旧後に再判定する保留を古い順に返す。
func (q *Queries) ListAwaitingSubmissions(ctx context.Context, limit int32) ([]ListAwaitingSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listAwaitingSubmissions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAwaitingSubmissionsRow
	for rows.Next() {
		var i ListAwaitingSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.SourceRecordID,
			&i.Body,
			&i.KoWritten,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingPooled = `-- name: MarkPendingPooled :exec
UPDATE pending_submission
SET status = 'pooled', promoted_tanzaku_id = $2, resolved_at = now()
WHERE id = $1
`

type MarkPendingPooledParams struct {
	ID                uuid.UUID
	PromotedTanzakuID pgtype.UUID
}

// 再判定で安全になり昇格した保留を pooled にする。
func (q *Queries) MarkPendingPooled(ctx context.Context, arg MarkPendingPooledParams) error {
	_, err := q.db.Exec(ctx, markPendingPooled, arg.ID, arg.PromotedTanzakuID)
	return err
}

const markPendingRejected = `-- name: MarkPendingRejected :exec
UPDATE pending_submission
SET status = 'rejected', last_error = $2, resolved_at = now()
WHERE id = $1
`

type MarkPendingRejectedParams struct {
	ID        uuid.UUID
	LastError *string
}

// 再判定で不適切と確定した保留を rejected にする。
func (q *Queries) MarkPendingRejected(ctx context.Context, arg MarkPendingRejectedParams) error {
	_, err := q.db.Exec(ctx, markPendingRejected, arg.ID, arg.LastError)
	return err
}
