// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO record (owner_id, body, ko_written)
VALUES ($1, $2, $3)
RETURNING id, owner_id, body, ko_written, created_at
`

type CreateRecordParams struct {
	OwnerID   uuid.UUID
	Body      string
	KoWritten int16
}

type CreateRecordRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Body      string
	KoWritten int16
	CreatedAt time.Time
}

// 文箱に記録を 1 枚保存する。
func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (CreateRecordRow, error) {
	row := q.db.QueryRow(ctx, createRecord, arg.OwnerID, arg.Body, arg.KoWritten)
	var i CreateRecordRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.KoWritten,
		&i.CreatedAt,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, owner_id, body, ko_written, created_at
FROM record
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetRecordParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type GetRecordRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Body      string
	KoWritten int16
	CreatedAt time.Time
}

// 本人の記録を 1 枚引く（owner_id を必ず条件に入れて他人のものを返さない）。
func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (GetRecordRow, error) {
	row := q.db.QueryRow(ctx, getRecord, arg.ID, arg.OwnerID)
	var i GetRecordRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.KoWritten,
		&i.CreatedAt,
	)
	return i, err
}

const listRecordsByOwner = `-- name: ListRecordsByOwner :many
SELECT id, owner_id, body, ko_written, created_at
FROM record
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY ko_written ASC, created_at DESC
`

type ListRecordsByOwnerRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Body      string
	KoWritten int16
	CreatedAt time.Time
}

// 本人の文箱を候別・新しい順に並べて返す（owner-only: owner_id で必ず絞る）。
func (q *Queries) ListRecordsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListRecordsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listRecordsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsByOwnerRow
	for rows.Next() {
		var i ListRecordsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.KoWritten,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
