// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO report (tanzaku_id, reporter_id, reason, note)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateReportParams struct {
	TanzakuID  uuid.UUID
	ReporterID uuid.UUID
	Reason     string
	Note       *string
}

// 受け手の通報を記録する（同じ一枚への二重通報は UNIQUE が弾く）。
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TanzakuID,
		arg.ReporterID,
		arg.Reason,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveReport = `-- name: ResolveReport :exec
UPDATE report
SET resolution = $2, resolved_at = now()
WHERE id = $1
`

type ResolveReportParams struct {
	ID         uuid.UUID
	Resolution *string
}

// 再判定の結果で通報を決着させる。
func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) error {
	_, err := q.db.Exec(ctx, resolveReport, arg.ID, arg.Resolution)
	return err
}
