// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tanzaku_origin.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTanzakuOrigin = `-- name: CreateTanzakuOrigin :exec
INSERT INTO tanzaku_origin (tanzaku_id, author_id, source_record_id)
VALUES ($1, $2, $3)
`

type CreateTanzakuOriginParams struct {
	TanzakuID      uuid.UUID
	AuthorID       uuid.UUID
	SourceRecordID pgtype.UUID
}

// 著者特定の私的リンクを作る（プール時・運営/モデレーションのみ参照、受け手向けに JOIN しない）。
func (q *Queries) CreateTanzakuOrigin(ctx context.Context, arg CreateTanzakuOriginParams) error {
	_, err := q.db.Exec(ctx, createTanzakuOrigin, arg.TanzakuID, arg.AuthorID, arg.SourceRecordID)
	return err
}

const getOriginForReview = `-- name: GetOriginForReview :one
SELECT t.id, t.body, t.status, o.author_id, o.source_record_id
FROM tanzaku t
JOIN tanzaku_origin o ON o.tanzaku_id = t.id
WHERE t.id = $1
`

type GetOriginForReviewRow struct {
	ID             uuid.UUID
	Body           string
	Status         string
	AuthorID       uuid.UUID
	SourceRecordID pgtype.UUID
}

// 再判定/保全のために一枚の本文と著者を引く（受け手向けには使わない運営専用クエリ）。
func (q *Queries) GetOriginForReview(ctx context.Context, id uuid.UUID) (GetOriginForReviewRow, error) {
	row := q.db.QueryRow(ctx, getOriginForReview, id)
	var i GetOriginForReviewRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Status,
		&i.AuthorID,
		&i.SourceRecordID,
	)
	return i, err
}
