// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tanzaku.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const expirePooledBefore = `-- name: ExpirePooledBefore :execrows
UPDATE tanzaku
SET status = 'expired'
WHERE status = 'pooled' AND pooled_at < $1
`

// 指定時刻より前にプールされた未配信を expired にする（候TTL）。
func (q *Queries) ExpirePooledBefore(ctx context.Context, pooledAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expirePooledBefore, pooledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDelivered = `-- name: MarkDelivered :exec
UPDATE tanzaku
SET status = 'delivered', author_id = NULL
WHERE id = $1
`

// 配信済みにし、著者を剥がして匿名化する。
func (q *Queries) MarkDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDelivered, id)
	return err
}

const pickOldestPooledForRecipient = `-- name: PickOldestPooledForRecipient :one
SELECT id
FROM tanzaku
WHERE status = 'pooled' AND author_id IS DISTINCT FROM $1
ORDER BY pooled_at ASC, id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

// 受け手が著者でない最古の未配信を 1 枚、行ロックして引く（同一バッチ内の取り合いを防ぐ）。
func (q *Queries) PickOldestPooledForRecipient(ctx context.Context, authorID pgtype.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, pickOldestPooledForRecipient, authorID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const poolTanzaku = `-- name: PoolTanzaku :one
INSERT INTO tanzaku (author_id, body, ko_written, is_official)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, body, ko_written, status, pooled_at, is_official
`

type PoolTanzakuParams struct {
	AuthorID   pgtype.UUID
	Body       string
	KoWritten  int16
	IsOfficial bool
}

// 記録の複製を未配信プールへ投入する（風に乗せる）。
func (q *Queries) PoolTanzaku(ctx context.Context, arg PoolTanzakuParams) (Tanzaku, error) {
	row := q.db.QueryRow(ctx, poolTanzaku,
		arg.AuthorID,
		arg.Body,
		arg.KoWritten,
		arg.IsOfficial,
	)
	var i Tanzaku
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.KoWritten,
		&i.Status,
		&i.PooledAt,
		&i.IsOfficial,
	)
	return i, err
}
