// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users DEFAULT VALUES
RETURNING id, created_at, role, reputation, suspended_at
`

// 匿名アカウントを 1 件作る（role は既定の member）。
func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.Reputation,
		&i.SuspendedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, role, reputation, suspended_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.Reputation,
		&i.SuspendedAt,
	)
	return i, err
}
